### ISSUE TITLE
Incompatible with native menus on v0.16.X

### ISSUE THREAD

**Issue by argenos** [chetachiezikeuzor/MySnippets-Plugin#17]
I wanted to give you a heads-up about the new Insiders' version, which adds native menus to the app. That makes the menu that pops up from the status bar unusable (the toggles and buttons to open snippets are gone). I got this tip from Liam about how to fix this in a plugin:

> we added an override to the Menu component so that one can override the "native menus" option just for her menu. It needs to be set explicitly though

And here's the relevant part of the API:

https://github.com/obsidianmd/obsidian-api/blob/6b2138aa28fb6d6f58f78e6fabec02186fdc0f82/obsidian.d.ts#L2182

**Comment by chetachiezikeuzor** [comment]
Version 1.2.2+ should already take care of this. Unless the issue persists? Please let me know.

**Comment by andrezgz** [comment]
> ps up from the status bar unusable (the toggles and buttons to open snippets are gone). I got this tip from Liam about how to fix this in a plugin:

Nothing happens when clicking on the snippets icon on the status bar. I'm using version 1.2.3 on Windows.

Console log error, at least, for me:

```js
Uncaught TypeError: menu.setUseNativeMenu is not a function
    at snippetsMenu (plugin:mysnippets-plugin:114:14)
    at HTMLDivElement.eval (plugin:mysnippets-plugin:349:13)
```

This is the function related to the error:

```js
function snippetsMenu(app, plugin, settings) {
    const windowX = window.innerWidth;
    const windowY = window.innerHeight;
    const menuExists = document.querySelector(".menu.MySnippets-statusbar-menu");
    if (!menuExists) {
        const menu = new obsidian.Menu();
        menu.setUseNativeMenu(false);
        ...
```
