### ISSUE TITLE
Location of pop-up

### ISSUE THREAD

**Issue by DutchPete** [chetachiezikeuzor/MySnippets-Plugin#4]
When the status bar with the MySnippets icon is shown, and I open MySnippets with a hotkey, the pop-up appears in the bottom right corner of the screen, which makes sense.

When the status bar is hidden and I open MySnippets with the hotkey, the pop-up appears in the top left corner, which is counter-intuitive.

Is it possible to have the pop-up always appear in the bottom right corner?

**Comment by chetachiezikeuzor** [comment]
The issue may be that the pop up is configured for mobile aspect ratios. If that is the case, I'm a some css config will fix the problem. I will investigate when I get home! And thank you for your issue!

**Comment by chetachiezikeuzor** [comment]
When you say "when the status bar is hidden" what do you mean by this? Are you using a plugin to hide the status bar or a css snippet?

**Comment by DutchPete** [comment]
When I filed the issues I was using a snippet. Now I am using the Hider plug-in and it is the same.

BTW, I realize that balancing desktop and mobile can be difficult sometimes, so if that is the case here, leave it as it is.

**Comment by DutchPete** [comment]
I noticed in the latest version that you fixed this, so I'll close this issue.
Many thanks.
